#
# Copyright (c) 2023 Gabriel Freitas <gabriel.estudy.reis@gmail.com>
#

install_requirements:
	pip install -r ./requirements.txt

runserver:
	cd ../scripts && \
	chmod +x runapis.sh && \
	./runapis.sh

test: